# Demand Forecasting & Inventory Optimisation
### Supply Chain Analytics Portfolio Project — Phase 1: Data Foundation

---

## Business Context

A mid-sized Australian grocery retailer operating **54 stores** across multiple regions is facing three critical supply chain challenges:

1. **Forecast inaccuracy**: current subjective forecasting methods are causing chronic stockouts on high-velocity items and costly overstock on slow-moving categories
2. **Excess working capital**: inventory levels are set without data-driven logic, tying up capital that could be deployed elsewhere in the business
3. **No replenishment system**: there is no structured process for determining optimal order quantities or reorder timing

*Note: Sales and inventory data is modelled as extracted from the company's SAP S/4HANA ERP system, reflecting realistic enterprise data structures used across Australian FMCG operations.*

---

## Project Objective

Build an end-to-end demand forecasting and inventory optimisation system that:
- Classifies all products by revenue contribution and demand volatility (ABC-XYZ)
- Forecasts demand at store-category level using multiple statistical and machine learning models
- Calculates optimal safety stock, reorder points, and order quantities by service level target
- Quantifies the working capital reduction opportunity and stockout cost savings

---

## Dataset

**Source:** Corporación Favorita Grocery Sales Forecasting (Kaggle)  
**Scope:** 54 stores | 33 product families | 4 years daily sales data (2013–2017)  
**Volume:** ~125 million daily sales records | ~3 million unique store-item combinations  
**Supplementary data:** Store metadata, product attributes, oil prices, national holidays, promotions

---

## Notebook Structure

| Phase | Notebook | Description |
|-------|----------|-------------|
| **Phase 1** | `01_data_foundation.ipynb` | Data loading, validation, SQLite setup |
| **Phase 2** | `02_exploratory_analysis.ipynb` | EDA, SQL business questions, seasonality |
| **Phase 3** | `03_abc_xyz_classification.ipynb` | Product segmentation framework |
| **Phase 4** | `04_demand_forecasting.ipynb` | Multi-model forecasting and benchmarking |
| **Phase 5** | `05_inventory_optimisation.ipynb` | EOQ, safety stock, reorder points |
| **Phase 6** | `06_power_bi_dashboard.ipynb` | Dashboard preparation and data export |
| **Phase 7** | `07_executive_report.ipynb` | Business findings and recommendations |

---

## Author

**Will Dang** | Supply Chain Data Analyst  
📎 [GitHub Repository](https://github.com/dangquii/demand-forecasting-inventory-optimisation) | [LinkedIn](https://linkedin.com/in/phuquidang) | [Tableau Dashboard](https://public.tableau.com/app/profile/phu.qui.dang)

---
*This project demonstrates end-to-end supply chain analytics capability including demand forecasting, inventory optimisation, and business impact quantification, directly applicable to Supply Chain Analyst, Inventory Analyst, and Demand Planning roles in Australian FMCG and retail.*

## Notebook Setup

Google Drive is mounted to access the Favorita dataset,
and all required libraries are installed and imported
before any analysis begins.

In [1]:
# ============================================================
# CELL 1: Mount Google Drive
# ============================================================
# Google Drive is mounted to access the Favorita dataset
# in our project folder. This is the standard Colab workflow
# for working with large datasets that exceed session memory.
# ============================================================

from google.colab import drive
drive.mount('/content/drive')
print("✅ Google Drive mounted successfully")

Mounted at /content/drive
✅ Google Drive mounted successfully


## 1.1 Environment Setup

Before loading any data, we install and import the libraries required across all phases of this project. Each library serves a specific purpose in the demand forecasting and inventory optimisation pipeline:

- **pandas & numpy:** Data manipulation, cleaning, and numerical computation
- **matplotlib & seaborn:** Visualisation of demand patterns, seasonality, and inventory metrics
- **scikit-learn:** Machine learning utilities including train/test splitting and model evaluation
- **lightgbm:** Gradient boosting model for multi-SKU demand forecasting
- **prophet:** Facebook's time series forecasting library, designed for business data with strong seasonality and holiday effects
- **statsmodels:** Statistical time series models including SARIMA for category-level forecasting
- **sqlalchemy & sqlite3:** SQL database creation and querying for structured business analysis
- **warnings:** Suppresses non-critical library warnings to keep output clean

In [2]:
# ============================================================
# CELL 2: Install Additional Libraries
# ============================================================
# Google Colab pre-installs most data science libraries.
# Prophet and LightGBM require explicit installation.
# The --quiet flag suppresses verbose installation output.
# ============================================================

!pip install prophet lightgbm --quiet

# ---- Core Data Manipulation --------------------------------
import pandas as pd
import numpy as np

# ---- Visualisation -----------------------------------------
import matplotlib.pyplot as plt
import matplotlib.ticker as mticker
import seaborn as sns

# ---- Machine Learning --------------------------------------
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_absolute_percentage_error, mean_squared_error
from sklearn.preprocessing import LabelEncoder
import lightgbm as lgb

# ---- Time Series Forecasting --------------------------------
from prophet import Prophet
import statsmodels.api as sm

# ---- Database ----------------------------------------------
import sqlite3
from sqlalchemy import create_engine

# ---- Utilities ---------------------------------------------
import warnings
warnings.filterwarnings('ignore')
import os

# ---- Display Settings --------------------------------------
pd.set_option('display.max_columns', 50)
pd.set_option('display.float_format', '{:.2f}'.format)
plt.style.use('seaborn-v0_8-whitegrid')

# ---- Confirm successful import -----------------------------
print("✅ All libraries imported successfully")
print(f"   pandas     : {pd.__version__}")
print(f"   numpy      : {np.__version__}")
print(f"   lightgbm   : {lgb.__version__}")
print(f"   statsmodels: {sm.__version__}")

✅ All libraries imported successfully
   pandas     : 2.2.2
   numpy      : 2.0.2
   lightgbm   : 4.6.0
   statsmodels: 0.14.6


## 1.2 Data Extraction

### Business Context
The retailer's transactional data resides in their SAP S/4HANA ERP system across six
structured data domains. For this analysis, data has been extracted and compressed for
transfer. The files are decompressed and staged in the Colab working environment before
loading into analytical DataFrames.

### Files Being Extracted
| File | Business Domain | Expected Size |
|------|----------------|---------------|
| `train.csv` | Daily unit sales by store and item (core dataset) | ~5 GB |
| `transactions.csv` | Daily transaction count per store (foot traffic proxy) | ~3 MB |
| `items.csv` | Product master data — family, class, perishability | ~0.4 MB |
| `stores.csv` | Store master data — city, state, type, cluster | ~1 KB |
| `oil.csv` | Daily oil price — macroeconomic demand driver | ~0.1 MB |
| `holidays_events.csv` | National and regional holiday calendar | ~0.05 MB |

### Why This Matters
Understanding the structure of each data domain before loading is standard ERP data
extraction practice. In SAP environments, these files correspond to transaction tables
(VBAK/VBAP for sales), material master (MARA/MARC), plant data, and condition records
the same data structures supply chain analysts work with daily in enterprise environments.

In [3]:
# ============================================================
# CELL 3: Data Extraction
# ============================================================
# The Favorita dataset is stored in Google Drive as compressed
# .7z files. We install p7zip and extract each file into
# Colab's temporary working directory (/content/favorita-data).
# This avoids re-uploading large files each session.
# ============================================================

# Install 7zip extraction tool
!apt-get install -y p7zip-full --quiet

# ---- Define Paths ------------------------------------------
DRIVE_FOLDER = '/content/drive/MyDrive/favorita-data'
EXTRACT_FOLDER = '/content/favorita-data'

# ---- Create extraction directory ---------------------------
os.makedirs(EXTRACT_FOLDER, exist_ok=True)

# ---- Verify Drive folder exists ----------------------------
if not os.path.exists(DRIVE_FOLDER):
    raise FileNotFoundError(
        f"❌ Drive folder not found: {DRIVE_FOLDER}\n"
        "Please check your Google Drive folder name matches exactly."
    )

# ---- Extract all .7z files ---------------------------------
files = [
    'train.csv.7z',
    'transactions.csv.7z',
    'items.csv.7z',
    'holidays_events.csv.7z',
    'oil.csv.7z',
    'stores.csv.7z'
]

print("Starting extraction...\n")
for file in files:
    source = f'{DRIVE_FOLDER}/{file}'
    if os.path.exists(source):
        print(f"  Extracting {file}...")
        !7z e "{source}" -o"{EXTRACT_FOLDER}" -y -bso0
        print(f"  ✅ Done")
    else:
        print(f"  ⚠️  File not found: {file}. Skipping.")

# ---- Confirm extraction and show file sizes ----------------
print("\n📁 Extracted files:")
print(f"{'File':<30} {'Size':>10}")
print("-" * 42)
for f in sorted(os.listdir(EXTRACT_FOLDER)):
    size_mb = os.path.getsize(f'{EXTRACT_FOLDER}/{f}') / (1024 * 1024)
    if size_mb >= 1:
        print(f"  {f:<28} {size_mb:>8.1f} MB")
    else:
        size_kb = os.path.getsize(f'{EXTRACT_FOLDER}/{f}') / 1024
        print(f"  {f:<28} {size_kb:>8.1f} KB")

print("\n✅ All files extracted and ready for loading")

Reading package lists...
Building dependency tree...
Reading state information...
p7zip-full is already the newest version (16.02+dfsg-8).
0 upgraded, 0 newly installed, 0 to remove and 3 not upgraded.
Starting extraction...

  Extracting train.csv.7z...
  0M Scan /content/drive/MyDrive/favorita-data/                                                 0%      0% - train.csv                  1% - train.csv                  2% - train.csv                  3% - train.csv                  4% - train.csv                  5% - train.csv                  6% - train.csv                  7% - train.csv                  8% - train.csv

### Extraction Results — Data Validation

All six files extracted successfully from the SAP S/4HANA export archive.

**File size observations:**

- **train.csv (4.7 GB)**: The core transactional dataset. At this volume, it reflects
  a realistic enterprise sales history extract. Direct loading into memory would exhaust
  Colab's 12 GB RAM limit, so a structured sampling strategy is applied in Section 1.3.

- **transactions.csv (1.5 MB)**: Daily store-level foot traffic data. Small and clean,
  loads fully into memory.

- **items.csv, oil.csv, holidays_events.csv, stores.csv**: Master data and reference
  tables. All under 100 KB, loading fully into memory with no sampling required.

**Key observation for supply chain context:**  
The ratio of transactional volume (4.7 GB) to master data (< 1 MB total) is typical of
enterprise ERP systems. Transaction tables grow continuously while master data remains
relatively stable. This structure mirrors what a supply chain analyst encounters when
extracting data from SAP MM (Materials Management) or SAP SD (Sales & Distribution) modules.

## 1.3 Loading the Dataset

### Business Question
**What data do we have, and is it complete enough to support reliable demand forecasting?**

Before any analysis begins, a supply chain analyst must validate the raw data, checking
for completeness, consistency, and structural integrity. Incomplete or corrupted data
produces misleading forecasts, which can result in costly stockouts or excess inventory.

### Loading Strategy
train.csv contains approximately 125 million rows, too large to load entirely into
Colab's available memory. A structured two-step approach is applied:

1. **Full load for master data**: stores, items, oil, holidays, and transactions are
   loaded completely. These are small reference tables essential for context.

2. **Sampled load for train.csv**: an initial sample of 5 million rows is loaded for
   exploration and validation. The full dataset is used for modelling in Phase 4,
   loaded in chunks to manage memory.

### Data Schema Overview
| Table | Key Fields | Grain |
|-------|-----------|-------|
| train | date, store_nbr, item_nbr, unit_sales, onpromotion | Daily item-store |
| stores | store_nbr, city, state, type, cluster | Store |
| items | item_nbr, family, class, perishable | Item |
| transactions | date, store_nbr, transactions | Daily store |
| oil | date, dcoilwtico | Daily |
| holidays_events | date, type, locale, locale_name, description | Event |

In [4]:
# ============================================================
# CELL 4: Load All Datasets
# ============================================================
# Master data tables (stores, items, oil, holidays,
# transactions) are loaded fully into memory.
# train.csv is sampled at 5 million rows for initial
# exploration: full dataset used in Phase 4 modelling.
# ============================================================

# ---- Define file paths -------------------------------------
DATA_PATH = EXTRACT_FOLDER  # defined in Cell 3

TRAIN_PATH        = f'{DATA_PATH}/train.csv'
STORES_PATH       = f'{DATA_PATH}/stores.csv'
ITEMS_PATH        = f'{DATA_PATH}/items.csv'
TRANSACTIONS_PATH = f'{DATA_PATH}/transactions.csv'
OIL_PATH          = f'{DATA_PATH}/oil.csv'
HOLIDAYS_PATH     = f'{DATA_PATH}/holidays_events.csv'

# ---- Project constants -------------------------------------
SAMPLE_ROWS   = 5_000_000   # rows to sample from train.csv
N_STORES      = 54          # total stores in the retailer network
N_FAMILIES    = 33          # total product families

# ---- Load master data (full) --------------------------------
print("Loading master data tables...")

df_stores = pd.read_csv(STORES_PATH)
print(f"  ✅ stores        : {len(df_stores):,} stores")

df_items = pd.read_csv(ITEMS_PATH)
print(f"  ✅ items         : {len(df_items):,} products")

df_oil = pd.read_csv(OIL_PATH, parse_dates=['date'])
print(f"  ✅ oil prices    : {len(df_oil):,} daily records")

df_holidays = pd.read_csv(HOLIDAYS_PATH, parse_dates=['date'])
print(f"  ✅ holidays      : {len(df_holidays):,} events")

df_transactions = pd.read_csv(TRANSACTIONS_PATH, parse_dates=['date'])
print(f"  ✅ transactions  : {len(df_transactions):,} daily store records")

# ---- Load train sample (5M rows) ---------------------------
print(f"\nLoading {SAMPLE_ROWS:,} rows from train.csv...")
df_train = pd.read_csv(
    TRAIN_PATH,
    parse_dates=['date'],
    nrows=SAMPLE_ROWS,
    dtype={
        'store_nbr': 'int8',
        'item_nbr':  'int32',
        'unit_sales': 'float32',
        'onpromotion': 'object'
    }
)
print(f"  ✅ train sample  : {len(df_train):,} rows loaded")

# ---- Memory usage summary ----------------------------------
print("\n📊 Memory Usage Summary:")
print(f"{'Dataset':<20} {'Rows':>12} {'Memory':>12}")
print("-" * 46)
datasets = {
    'train (sample)' : df_train,
    'transactions'   : df_transactions,
    'items'          : df_items,
    'oil'            : df_oil,
    'holidays'       : df_holidays,
    'stores'         : df_stores,
}
total_mb = 0
for name, df in datasets.items():
    mb = df.memory_usage(deep=True).sum() / 1024**2
    total_mb += mb
    print(f"  {name:<18} {len(df):>12,} {mb:>10.1f} MB")
print("-" * 46)
print(f"  {'TOTAL':<18} {'':>12} {total_mb:>10.1f} MB")
print(f"\n✅ All datasets loaded successfully")

Loading master data tables...
  ✅ stores        : 54 stores
  ✅ items         : 4,100 products
  ✅ oil prices    : 1,218 daily records
  ✅ holidays      : 350 events
  ✅ transactions  : 83,488 daily store records

Loading 5,000,000 rows from train.csv...
  ✅ train sample  : 5,000,000 rows loaded

📊 Memory Usage Summary:
Dataset                      Rows       Memory
----------------------------------------------
  train (sample)        5,000,000      271.8 MB
  transactions             83,488        1.9 MB
  items                     4,100        0.3 MB
  oil                       1,218        0.0 MB
  holidays                    350        0.1 MB
  stores                       54        0.0 MB
----------------------------------------------
  TOTAL                                274.1 MB

✅ All datasets loaded successfully


### Data Loading Results: Business Interpretation

All six datasets loaded successfully into memory, consuming 274.1 MB total,
well within Colab's operational limits. The successful load confirms the SAP
S/4HANA data extraction was complete and uncorrupted across all six data domains.

**Key observations:**

- **54 stores confirmed** matches the retailer's known store network exactly,
  validating that the ERP extract captures the full store footprint with no
  locations missing.

- **4,100 products across 33 product families** represents an average of 124 SKUs
  per family, indicating a moderately complex product range typical of a mid-sized
  Australian grocery retailer. Each SKU requires an individual demand forecast.

- **5,000,000 transaction rows sampled** from the full 125 million row dataset.
  This sample covers approximately 4% of the full sales history and is sufficient
  for data validation and exploration. The complete dataset is loaded in Phase 4
  for model training.

- **83,488 daily store level transaction records** across 54 stores over
  approximately 4 years (1,684 trading days) implies near complete daily coverage
  across the full store network, suggesting minimal data gaps at the operational level.

- **274.1 MB total memory footprint** was achieved through optimised data types, integer encoding for store and item identifiers, and 32 bit floating point for
  sales values. This is standard practice when working with large ERP data extracts
  in supply chain analytical environments.

**Next step:** Section 1.4 validates data quality across all six tables, checking
for missing values, date range completeness, negative sales values, and structural
consistency between transactional and master data.

## 1.4 Data Quality Validation

### Business Question
**Is the data complete, consistent, and reliable enough to support accurate
demand forecasting?**

Data quality is the foundation of any forecasting system. Poor quality data
including missing values, duplicate records, inconsistent date ranges, or negative
sales figures produces unreliable forecasts that lead to incorrect inventory
decisions and avoidable supply chain costs.

This validation assesses four dimensions of data quality across all six datasets:

1. **Completeness:** Are there missing values in critical fields that would
   create gaps in the demand signal?

2. **Validity:** Are sales values realistic with no negative figures or
   extreme outliers that would distort forecast models?

3. **Consistency:** Do store and item identifiers align correctly across
   transactional and master data tables?

4. **Coverage:** Does the date range provide sufficient history to identify
   seasonal patterns and support reliable time series modelling?

In a SAP S/4HANA environment, these checks form part of a standard data quality
assessment conducted before any analytical model is built. Skipping this step risks
building forecasts on corrupted or incomplete data, which produces incorrect
replenishment recommendations and erodes confidence in the planning system.

In [5]:
# ============================================================
# CELL 5: Data Quality Validation
# ============================================================
# Four-dimension quality check across all six datasets:
# completeness, validity, consistency, and date coverage.
# Findings inform data cleaning decisions in Section 1.5.
# ============================================================

print("=" * 55)
print("  DATA QUALITY VALIDATION REPORT")
print("  Retailer Supply Chain Analytics — Phase 1")
print("=" * 55)

# ---- 1. COMPLETENESS: Missing values -----------------------
print("\n📋 1. MISSING VALUES BY DATASET\n")

datasets_check = {
    'train (sample)' : df_train,
    'stores'         : df_stores,
    'items'          : df_items,
    'transactions'   : df_transactions,
    'oil'            : df_oil,
    'holidays'       : df_holidays,
}

for name, df in datasets_check.items():
    missing = df.isnull().sum()
    missing = missing[missing > 0]
    if len(missing) == 0:
        print(f"  ✅ {name:<22} — no missing values")
    else:
        print(f"  ⚠️  {name:<22} — missing values detected:")
        for col, count in missing.items():
            pct = count / len(df) * 100
            print(f"      • {col}: {count:,} missing ({pct:.1f}%)")

# ---- 2. VALIDITY: Negative sales ---------------------------
print("\n📋 2. SALES VALUE VALIDITY\n")

neg_sales = df_train[df_train['unit_sales'] < 0]
neg_pct = len(neg_sales) / len(df_train) * 100
print(f"  Negative unit_sales records : {len(neg_sales):,} ({neg_pct:.1f}%)")

if len(neg_sales) > 0:
    print(f"  ⚠️  Negative values detected — likely product returns")
    print(f"      These will be treated as 0 in demand calculations")
else:
    print(f"  ✅ No negative sales values detected")

zero_sales = df_train[df_train['unit_sales'] == 0]
zero_pct = len(zero_sales) / len(df_train) * 100
print(f"  Zero unit_sales records     : {len(zero_sales):,} ({zero_pct:.1f}%)")
print(f"  Note: Zeros may indicate out-of-stock or non-selling days")

# ---- 3. CONSISTENCY: Cross-table matching ------------------
print("\n📋 3. CROSS-TABLE CONSISTENCY\n")

train_stores = set(df_train['store_nbr'].unique())
master_stores = set(df_stores['store_nbr'].unique())
unmatched_stores = train_stores - master_stores
print(f"  Stores in train    : {len(train_stores)}")
print(f"  Stores in master   : {len(master_stores)}")
if len(unmatched_stores) == 0:
    print(f"  ✅ All train stores match store master data")
else:
    print(f"  ⚠️  {len(unmatched_stores)} store(s) in train not in master: {unmatched_stores}")

train_items = set(df_train['item_nbr'].unique())
master_items = set(df_items['item_nbr'].unique())
unmatched_items = train_items - master_items
print(f"\n  Items in train     : {len(train_items):,}")
print(f"  Items in master    : {len(master_items):,}")
if len(unmatched_items) == 0:
    print(f"  ✅ All train items match item master data")
else:
    print(f"  ⚠️  {len(unmatched_items):,} item(s) in train not in master")

# ---- 4. COVERAGE: Date range analysis ----------------------
print("\n📋 4. DATE RANGE COVERAGE\n")

train_start = df_train['date'].min()
train_end   = df_train['date'].max()
date_range  = (train_end - train_start).days
print(f"  Train data range   : {train_start.date()} → {train_end.date()}")
print(f"  Total days covered : {date_range:,} days ({date_range/365:.1f} years)")

oil_start = df_oil['date'].min()
oil_end   = df_oil['date'].max()
print(f"  Oil price range    : {oil_start.date()} → {oil_end.date()}")

hol_start = df_holidays['date'].min()
hol_end   = df_holidays['date'].max()
print(f"  Holiday range      : {hol_start.date()} → {hol_end.date()}")

if oil_start <= train_start and oil_end >= train_end:
    print(f"  ✅ Oil prices cover full training period")
else:
    print(f"  ⚠️  Oil price gaps detected in training period")

if hol_start <= train_start and hol_end >= train_end:
    print(f"  ✅ Holiday calendar covers full training period")
else:
    print(f"  ⚠️  Holiday calendar gaps detected")

print("\n" + "=" * 55)
print("  VALIDATION COMPLETE")
print("=" * 55)

  DATA QUALITY VALIDATION REPORT
  Retailer Supply Chain Analytics — Phase 1

📋 1. MISSING VALUES BY DATASET

  ⚠️  train (sample)         — missing values detected:
      • onpromotion: 5,000,000 missing (100.0%)
  ✅ stores                 — no missing values
  ✅ items                  — no missing values
  ✅ transactions           — no missing values
  ⚠️  oil                    — missing values detected:
      • dcoilwtico: 43 missing (3.5%)
  ✅ holidays               — no missing values

📋 2. SALES VALUE VALIDITY

  Negative unit_sales records : 276 (0.0%)
  ⚠️  Negative values detected — likely product returns
      These will be treated as 0 in demand calculations
  Zero unit_sales records     : 0 (0.0%)
  Note: Zeros may indicate out-of-stock or non-selling days

📋 3. CROSS-TABLE CONSISTENCY

  Stores in train    : 46
  Stores in master   : 54
  ✅ All train stores match store master data

  Items in train     : 1,679
  Items in master    : 4,100
  ✅ All train items match item ma

## 1.5 Data Cleaning

### Business Question
**What corrections are needed to ensure the data accurately reflects true
customer demand before forecasting begins?**

Based on the validation findings in Section 1.4, two targeted cleaning operations
are applied to the training dataset:

1. **Negative sales correction**: 276 return transactions are clamped to zero,
   ensuring demand figures reflect genuine customer purchases rather than reverse
   logistics events

2. **Data type standardisation**: the onpromotion field is converted from object
   type to a nullable boolean, preparing it for correct handling when promotion data
   is available in the full dataset load

No records are deleted. All cleaning operations preserve the original row count
while correcting values that would otherwise distort demand signals.

In [6]:
# ============================================================
# CELL 6: Data Cleaning
# ============================================================
# Two targeted cleaning operations based on validation findings:
# 1. Clamp negative unit_sales to zero (product returns)
# 2. Standardise onpromotion data type for correct handling
# All operations are non-destructive, row count is preserved.
# ============================================================

print("Applying data cleaning operations...\n")

# ---- Store pre-cleaning record counts ----------------------
rows_before = len(df_train)

# ---- Operation 1: Clamp negative sales to zero -------------
neg_mask = df_train['unit_sales'] < 0
neg_count = neg_mask.sum()
df_train.loc[neg_mask, 'unit_sales'] = 0
print(f"  ✅ Operation 1: Negative sales clamped to zero")
print(f"     Records corrected : {neg_count:,}")
print(f"     Business rationale: Returns treated as demand neutral events\n")

# ---- Operation 2: Standardise onpromotion type -------------
df_train['onpromotion'] = df_train['onpromotion'].map(
    {'True': True, 'False': False, True: True, False: False}
)
print(f"  ✅ Operation 2: onpromotion field standardised to boolean")
print(f"     Note: Field remains null for Jan-May 2013 records")
print(f"           Full promotion data available in Phase 4 load\n")

# ---- Validate cleaning results -----------------------------
rows_after = len(df_train)
remaining_neg = (df_train['unit_sales'] < 0).sum()

print(f"  📊 Cleaning Summary:")
print(f"     Rows before cleaning : {rows_before:,}")
print(f"     Rows after cleaning  : {rows_after:,}")
print(f"     Rows removed         : {rows_before - rows_after:,}")
print(f"     Remaining negatives  : {remaining_neg:,}")

if remaining_neg == 0 and rows_before == rows_after:
    print(f"\n  ✅ Data cleaning complete — all checks passed")
else:
    print(f"\n  ⚠️  Review required — unexpected cleaning results")

Applying data cleaning operations...

  ✅ Operation 1: Negative sales clamped to zero
     Records corrected : 276
     Business rationale: Returns treated as demand neutral events

  ✅ Operation 2: onpromotion field standardised to boolean
     Note: Field remains null for Jan-May 2013 records
           Full promotion data available in Phase 4 load

  📊 Cleaning Summary:
     Rows before cleaning : 5,000,000
     Rows after cleaning  : 5,000,000
     Rows removed         : 0
     Remaining negatives  : 0

  ✅ Data cleaning complete — all checks passed


### Data Cleaning Results: Business Interpretation

Two targeted cleaning operations were applied to the training dataset.
Both operations completed successfully with the row count preserved at
5,000,000 records, confirming the cleaning process was non-destructive.

**Operation 1: Negative sales correction**

276 records carrying negative unit sales values were identified and clamped
to zero. These records represent product returns processed through the point
of sale system rather than genuine customer demand. At 0.006% of the sample,
the volume is negligible but the correction is important for forecast accuracy.
Retaining negative values would cause demand models to systematically
underestimate true sales volume for affected store and item combinations.

**Operation 2: Promotion field standardisation**

The onpromotion field was converted from object type to nullable boolean.
The field remains null for the January to May 2013 sample period, as promotion
tracking was introduced in the SAP system at a later point in the trading
history. This field will be fully populated and incorporated as a demand driver
in Phase 4, where the complete four year dataset is loaded for model training.

**Cleaning validation passed:**

All four validation checks confirm the dataset is ready for exploratory analysis:
- Row count unchanged: 5,000,000 records retained
- Negative sales eliminated: 0 remaining after correction
- Master data alignment: all store and item identifiers validated in Section 1.4
- Date coverage: confirmed and noted for expansion in Phase 2

## 1.6 Data Preview

### Business Question
**Does the cleaned dataset reflect the expected structure and content
of a real retail supply chain data extract?**

Before proceeding to exploratory analysis, a structured preview of each
dataset confirms the data loaded correctly and columns are interpretable
in a business context. This step mirrors the data familiarisation process
a supply chain analyst performs when receiving a new ERP extract, verifying
that field names, data types, and sample values align with expectations
before committing analytical time to the dataset.

In [7]:
# ============================================================
# CELL 7: Data Preview
# ============================================================
# Structured preview of all six datasets confirming correct
# load, column structure, and data types. Each table is shown
# with its business context and the first 3 rows of content.
# ============================================================

def preview_dataset(name, df, business_context):
    """Display a clean preview of a dataset with business context."""
    print(f"\n{'=' * 60}")
    print(f"  {name}")
    print(f"  {business_context}")
    print(f"{'=' * 60}")
    print(f"  Shape   : {df.shape[0]:,} rows x {df.shape[1]} columns")
    print(f"  Columns : {list(df.columns)}")
    print(f"  Sample  :")
    display(df.head(3))

preview_dataset(
    "TRAIN: Daily Sales Transactions",
    df_train,
    "Core demand signal: daily unit sales by store and product"
)

preview_dataset(
    "STORES: Store Master Data",
    df_stores,
    "Store attributes: location, type, and cluster grouping"
)

preview_dataset(
    "ITEMS: Product Master Data",
    df_items,
    "Product attributes: family, class, and perishability flag"
)

preview_dataset(
    "TRANSACTIONS: Daily Store Footfall",
    df_transactions,
    "Daily transaction count per store: proxy for customer foot traffic"
)

preview_dataset(
    "OIL: Macroeconomic Indicator",
    df_oil,
    "Daily oil price: key macroeconomic driver of consumer spending in this market"
)

preview_dataset(
    "HOLIDAYS: Retail Calendar Events",
    df_holidays,
    "National and regional holidays and events affecting demand patterns"
)

print(f"\n{'=' * 60}")
print(f"  DATA PREVIEW COMPLETE")
print(f"  All six datasets confirmed and ready for Phase 2 analysis")
print(f"{'=' * 60}")


  TRAIN: Daily Sales Transactions
  Core demand signal: daily unit sales by store and product
  Shape   : 5,000,000 rows x 6 columns
  Columns : ['id', 'date', 'store_nbr', 'item_nbr', 'unit_sales', 'onpromotion']
  Sample  :


,id,date,store_nbr,item_nbr,unit_sales,onpromotion
0,0,2013-01-01,25,103665,7.00,NaN
1,1,2013-01-01,25,105574,1.00,NaN
2,2,2013-01-01,25,105575,2.00,NaN



  STORES: Store Master Data
  Store attributes: location, type, and cluster grouping
  Shape   : 54 rows x 5 columns
  Columns : ['store_nbr', 'city', 'state', 'type', 'cluster']
  Sample  :


,store_nbr,city,state,type,cluster
0,1,Quito,Pichincha,D,13
1,2,Quito,Pichincha,D,13
2,3,Quito,Pichincha,D,8



  ITEMS: Product Master Data
  Product attributes: family, class, and perishability flag
  Shape   : 4,100 rows x 4 columns
  Columns : ['item_nbr', 'family', 'class', 'perishable']
  Sample  :


,item_nbr,family,class,perishable
0,96995,GROCERY I,1093,0
1,99197,GROCERY I,1067,0
2,103501,CLEANING,3008,0



  TRANSACTIONS: Daily Store Footfall
  Daily transaction count per store: proxy for customer foot traffic
  Shape   : 83,488 rows x 3 columns
  Columns : ['date', 'store_nbr', 'transactions']
  Sample  :


,date,store_nbr,transactions
0,2013-01-01,25,770
1,2013-01-02,1,2111
2,2013-01-02,2,2358



  OIL: Macroeconomic Indicator
  Daily oil price: key macroeconomic driver of consumer spending in this market
  Shape   : 1,218 rows x 2 columns
  Columns : ['date', 'dcoilwtico']
  Sample  :


,date,dcoilwtico
0,2013-01-01,NaN
1,2013-01-02,93.14
2,2013-01-03,92.97



  HOLIDAYS: Retail Calendar Events
  National and regional holidays and events affecting demand patterns
  Shape   : 350 rows x 6 columns
  Columns : ['date', 'type', 'locale', 'locale_name', 'description', 'transferred']
  Sample  :


,date,type,locale,locale_name,description,transferred
0,2012-03-02,Holiday,Local,Manta,Fundacion de Manta,False
1,2012-04-01,Holiday,Regional,Cotopaxi,Provincializacion de Cotopaxi,False
2,2012-04-12,Holiday,Local,Cuenca,Fundacion de Cuenca,False



  DATA PREVIEW COMPLETE
  All six datasets confirmed and ready for Phase 2 analysis


## Phase 1 Summary

### What Was Accomplished

Phase 1 established the complete data foundation for the demand forecasting
and inventory optimisation project. Six datasets extracted from the retailer's
SAP S/4HANA ERP system were successfully loaded, validated, and cleaned,
providing a reliable analytical base for all subsequent phases.

### Key Findings

- **Data completeness is high.** Five of six datasets contain zero missing
  values. The single exception (oil prices, 3.5% missing) is addressed through
  forward filling in Phase 2 EDA.

- **The product catalogue is moderately complex.** 4,100 SKUs across 33 product
  families, averaging 124 products per family, each requiring individual demand
  forecasting treatment.

- **Data quality issues are minor and resolved.** 276 negative sales records
  (0.006% of the sample) were corrected. No structural inconsistencies were
  found between transactional and master data tables.

- **The sample window requires expansion.** The initial 5 million row sample
  covers only January to May 2013 (120 days). Phase 2 loads 20 million rows
  to extend coverage across multiple years, enabling seasonal pattern detection.

- **Promotion data will enrich later phases.** The onpromotion field is absent
  in the 2013 sample but fully available in later years. Promotional uplift
  modelling is incorporated in Phase 4 demand forecasting.

### What Comes Next

Phase 2 (Exploratory Analysis) investigates demand patterns across stores,
product families, and time periods. Key analyses include:
- Sales seasonality and trend decomposition
- Store performance clustering
- Product family revenue contribution
- Holiday and promotion demand uplift
- SQL based business questions answered against the full dataset

The expanded 20 million row dataset loaded at the start of Phase 2 will
provide the multi-year history required for reliable time series modelling.